Fix/3518  fix t.map error
tracim/tracim pull request #3593
Opened 2020-09-15 15:09 UTC by raphj

#3518

This PR also refactors functions used to talk to the API. The fix is in the first commit.

## Checkpoints

**For developers**

- [X] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [X] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [X] Automated tests seem irrelevant

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2020-09-15 15:31 UTC, grignards commented
I understand your changes but fail to see why it fixes the issue's bug. Could you explain?

2020-09-15 15:45 UTC, gbonaspetti requested changes

2020-09-15 15:45 UTC, gbonaspetti commented on frontend_lib/src/action.async.js
> +export const baseFetch = (method, url, body, opts) =>
`opts` is used somewhere?

2020-09-15 15:45 UTC, gbonaspetti commented on frontend_app_admin_workspace_user/src/action.async.js
> +  baseFetch('GET', `${apiUrl}/users/${userId}/disabled`)
```suggestion
  baseFetch('PUT', `${apiUrl}/users/${userId}/disabled`)
```

2020-09-15 15:45 UTC, gbonaspetti commented on frontend_app_admin_workspace_user/src/action.async.js
> +  baseFetch('GET', `${apiUrl}/users/${userId}/enabled`)
```suggestion
  baseFetch('PUT', `${apiUrl}/users/${userId}/enabled`)
```

2020-09-15 15:45 UTC, gbonaspetti commented on frontend_app_workspace_advanced/src/action.async.js
> +    description: newDescription
Are you sure that the other parameters weren't necessary?

2020-09-15 17:23 UTC, raphj commented
@grignards 

So, the fix here: https://github.com/tracim/tracim/pull/3593/files#diff-b7ba43e69b6c83d21cf48be1406d6609R31
Fixes this issue, because the t.map error was caused by two things:

1. the frontend, instead of passing the workspace id given in the url parameter to open a content, gives the current workspace's id
2. it does not handle the 401 error it gets as a result.

This line fixes the first issue. The refactoring that I spent the afternoon on aimed to centralize the error handling to fix the second point, which I haven't had the time to do today. However, I agree with @gbonaspetti (in private messages): it is probably risky to ship Tracim 3.1.1 with this refactoring, so I suggest to merge this PR in develop when all the tests pass, but for tracim 3.1.1 restrict the fix to the one line that makes the frontend use the right workspace id.

2020-09-15 17:28 UTC, raphj commented on frontend_app_file/src/container/File.jsx
>    postShareLinksList,
```suggestion
  postShareLinksList
```

2020-09-15 17:29 UTC, raphj commented on frontend_app_html-document/src/action.async.js
>        raw_content: newContent
```suggestion
    label: label,
    raw_content: newContent
```

2020-09-15 17:30 UTC, raphj commented on frontend_app_workspace_advanced/src/action.async.js
> +export const getAppList = () =>
```suggestion
export const getAppList = (apiUrl) =>
```

2020-09-17 09:01 UTC, gbonaspetti approved these changes

2020-09-21 09:04 UTC, gbonaspetti commented
Tested on branch.

2020-09-21 09:09 UTC, merged