Feat/3604  add auto invite plugin
tracim/tracim pull request #3721
Opened 2020-10-21 10:21 UTC by inkhey

related to #3604 

## Checkpoints

**For developers**

- [ ] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2020-10-21 12:12 UTC, grignards requested changes
Only some grammar/typo on the documentation.

2020-10-21 12:12 UTC, grignards commented on backend/official_plugins/tracim_backend_autoinvite/README.md
> +- add all user to new created open space
```suggestion
- adds every new user to all open spaces
- adds all users to every created open space
```

2020-10-21 12:12 UTC, grignards commented on backend/official_plugins/README.md
> +You can active them by moving the plugins you need in `plugin.folder_path` dir.
```suggestion
This directory contains all official backend plugins
Those plugins are implemented using an experimental API that is planned to change: if you develop your own plugin using this API, expect it to break without notice.
You can enable them by moving the plugins you need in the `plugin.folder_path` directory.
```

2020-10-21 12:12 UTC, grignards commented on backend/official_plugins/README.md
> +## Officials Backend Plugins
```suggestion
## Official Backend Plugins
```

2020-10-21 15:12 UTC, grignards commented
And don't forget to use asf-algoo for this PR.

2020-10-23 07:57 UTC, grignards approved these changes

2020-10-23 11:36 UTC, raphj approved these changes

2020-10-23 11:48 UTC, closed without merging

2020-10-23 11:49 UTC, asf-algoo commented
moved to https://github.com/tracim/tracim/pull/3730