Feat/3824  autogenerate pre join space message
tracim/tracim pull request #3859
Opened 2020-11-19 15:05 UTC by asf-algoo

related to #3824 

## Checkpoints

**For developers**

- [ ] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2020-11-19 16:11 UTC, grignards requested changes

2020-11-19 16:11 UTC, grignards commented on backend/tracim_backend/lib/core/event.py
> +        max_event_history: int = -1,
```suggestion
        max_messages_count: int = -1,
```

2020-11-19 16:11 UTC, grignards commented on backend/tracim_backend/lib/core/event.py
> +    def generate_historic_workspaces_messages_for_user(
```suggestion
    def create_messages_history_for_user(
```

2020-11-20 08:46 UTC, inkhey commented on backend/tracim_backend/lib/core/event.py
> +        max_event_history: int = -1,
done

2020-11-20 08:46 UTC, inkhey commented on backend/tracim_backend/lib/core/event.py
> +    def generate_historic_workspaces_messages_for_user(
done.

2020-11-20 08:55 UTC, grignards approved these changes

2020-11-20 09:03 UTC, grignards commented
Tested on branch.

2020-11-20 13:08 UTC, inkhey commented
There was an issue with old sqlite version as in our current CI we do used:
- xenial(16.04) on python 3.7 which in travis included sqlite 3.11.
- bionic(18.04) on python 3.6 which in travis included sqlite 3.22.
- bionic(18.04) on python 3.5 which in travis included sqlite 3.22.

The JSON request to filter on workspace does a `JSON_QUOTE` which is an action added to sqlite 3.14, so it was not working with python 3.7 test. A similar sql query already exist in tracim code but is related to only an API test which is runned on python 3.6 only with sqlite 3.22, so we were not able to see the issue here: https://github.com/tracim/tracim/commit/697260b355d47369c485ba361ccceecc4d60579a .

After moving python 3.7 from xenial to bionic, i do get sqlite 3.22 on all database, so with it, we do not have any issue in CI.
We can clearly say we do support sqlite>3.22, and theorically support sqlite>=3.14 with JSON1 extension.

Because of this issue, i added a script for debugging sqlite version/extensions loaded more easily in both CI and dev environnement.

We need to verify which python sqlite version our docker image used, to be sure to not have bug there too.

2020-11-20 13:31 UTC, inkhey commented
After some research, it seems that python provided by Gnu/Linux distribution is build with`libsqlite3-0` library by default, which mean the version of this library is the version used by python (at least by default).
This explain why:
- xenial provided sqlite 3.11 : https://packages.ubuntu.com/xenial/libsqlite3-0
- bionic provided sqlite 3.22 : https://packages.ubuntu.com/bionic/libsqlite3-0
- our docker based on stretch use sqlite 3.16.2: https://packages.debian.org/fr/stretch/libsqlite3-0
 (verified manually too).

2020-11-20 15:21 UTC, grignards approved these changes

2020-11-25 15:03 UTC, raphj approved these changes

2020-11-25 15:03 UTC, raphj commented on backend/tracim_backend/lib/core/event.py
> +        related to given workspaces exist as message for user given.
```suggestion
        Generate, for the given user, messages for the last max_messages_count events that happened in the
        given workspace , if they do not already exist for this user.
```

2020-11-30 08:22 UTC, merged