feat(backend): only use flake8 + extensions to lint code
tracim/tracim pull request #3869
Opened 2020-11-23 19:46 UTC by grignards

This is easier to launch: `flake8` and also simplifies CI + pre-commit hooks.

## Checkpoints

**For developers**

- [ ] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2020-11-24 07:59 UTC, raphj approved these changes

2020-12-21 09:07 UTC, inkhey requested changes
To add black and isort to flake8 used by precommit,
you need to use `additional_dependencies`
see flake8 example here:
https://framagit.org/inkhey/pioupiou/-/blob/master/.pre-commit-config.yaml
for `flake8-bugbear` for example.

2020-12-21 09:59 UTC, grignards commented
Yes I saw it, but keeping a separate black & isort for pre-commit has the advantage that they do the needed changes automatically (and leave the staging to the developer). If we only use flake8 + its black and isort plugins we don't get this.

2020-12-21 12:37 UTC, inkhey commented
> Yes I saw it, but keeping a separate black & isort for pre-commit has the advantage that they do the needed changes automatically (and leave the staging to the developer). If we only use flake8 + its black and isort plugins we don't get this.

Ok, can you rename the PR name and description to make it consistent with the PR change ?

2020-12-21 14:21 UTC, inkhey approved these changes

2020-12-30 08:47 UTC, merged