fix(frontend): some translation and wording issues
tracim/tracim pull request #4120
Opened 2021-01-28 15:47 UTC by grignards

See #4114.

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [x] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link): translations are never tested automatically
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2021-01-28 15:54 UTC, raphj approved these changes

2021-01-29 10:15 UTC, gbonaspetti requested changes

2021-01-29 10:15 UTC, gbonaspetti commented on frontend/i18next.scanner/pt/translation.json
> +  "{{ count }} contribution _plural": "{{ count }} intervençãos ",
```suggestion
  "{{ count }} contribution _plural": "{{ count }} intervenções ",
```

2021-01-29 10:15 UTC, gbonaspetti commented on frontend/src/component/PublicProfile/Information.jsx
> +          {props.t('{{ count }} contribution ', { count: props.authoredContentRevisionsCount })}
```suggestion
          {props.t('{{ count }} intervention ', { count: props.authoredContentRevisionsCount })}
```

2021-01-29 10:17 UTC, gbonaspetti commented
During tests:
- The space activity feed breadcrumbs are not translated
![breadFeed](https://user-images.githubusercontent.com/35422692/106262546-80d8c780-6223-11eb-95a7-99cf09b9be4f.gif)

2021-01-29 15:30 UTC, raphj approved these changes

2021-01-29 15:30 UTC, raphj commented
I liked "contribution", though

2021-01-29 16:48 UTC, merged