Feat/4124  upgrade to font awesome 5
tracim/tracim pull request #4135
Opened 2021-02-01 16:54 UTC by Skylsmoi

https://github.com/tracim/tracim/issues/4124

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2021-02-01 16:57 UTC, Skylsmoi commented
regarding tests: I can't make a test for each modification I made, there would be way too many.
I have only updated the existing one that where testing icons

2021-02-01 17:00 UTC, Skylsmoi commented
Also note that the very high amount of line changed in this PR is due to the addition of font awesome 5 library in `fontend/dist/assets/font/fontawesome-free-5.15.2-web`

2021-02-02 09:15 UTC, gbonaspetti requested changes

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_app_gallery/src/container/Gallery.jsx
> +                  <i className='far fa-fw fa-trash-alt' />
```suggestion
                  <i className='fas fa-fw fa-trash-alt' />
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_app_thread/src/debug.js.sample
> +    faIcon: 'comments',
```suggestion
    faIcon: 'far fa-comments',
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_lib/src/component/FileDropzone/FileUploadList.jsx
> +            <i className='fas fa-fw fa-file-o m-1' />
```suggestion
            <i className='far fa-fw fa-file m-1' />
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_lib/src/component/NewMemberForm/NewMemberForm.jsx
> +                  <i className='name__adminmsg__icon fas fa-fw fa-lightbulb-o' />
```suggestion
                  <i className='name__adminmsg__icon far fa-fw fa-lightbulb' />
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_lib/src/component/OptionComponent/ArchiveDeleteContent.jsx
> +        <i className='far fa-fw fa-trash-alt' />
```suggestion
        <i className='fas fa-fw fa-trash-alt' />
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_lib/src/component/ShareLink/ShareLink.jsx
> +          <i className='fas fa-fw fa-files-o' />
```suggestion
          <i className='far fa-fw fa-files' />
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_lib/src/component/ShareLink/ShareLink.jsx
> +            <i className='far fa-fw fa-trash-' />
```suggestion
            <i className='far fa-fw fa-trash-alt' />
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_lib/src/component/Timeline/Timeline.jsx
> +                    <i className='fas fa-paper-plane' />
```suggestion
                    <i className='far fa-paper-plane' />
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_lib/src/helper.js
> +  faIcon: 'fas fa-comment',
```suggestion
  faIcon: 'far fa-comment',
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_lib/src/helper.js
> +  faIcon: 'fas fa-file-archive',
```suggestion
  faIcon: 'far fa-file-archive',
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_lib/src/helper.js
> +  faIcon: 'fas fa-trash-alt',
```suggestion
  faIcon: 'far fa-trash-alt',
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_lib/src/helper.js
> +  faIcon: 'fas fa-files',
```suggestion
  faIcon: 'far fa-files',
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_lib/src/helper.js
> +  faIcon: 'far fa-eye',
```suggestion
  faIcon: 'fas fa-eye',
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_lib/src/helper.js
> +  faIcon: 'fas fa-sun',
```suggestion
  faIcon: 'far fa-sun',
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_lib/test/fixture/app/agenda.js
> +  faIcon: 'far fa-calendar-alt',
```suggestion
  faIcon: 'fas fa-calendar-alt',
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_lib/test/fixture/sidebarEntryList.js
> +    fa_icon: 'comments',
```suggestion
    fa_icon: 'far fa-comments',
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_lib/test/fixture/sidebarEntryList.js
> +    fa_icon: 'file-text',
```suggestion
    fa_icon: 'far fa-file-text',
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_lib/test/fixture/sidebarEntryList.js
> +    fa_icon: 'picture',
```suggestion
    fa_icon: 'far fa-image',
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_lib/test/fixture/status.js
> +  faIcon: 'fas fa-square',
```suggestion
  faIcon: 'far fa-square',
```

2021-02-02 09:15 UTC, gbonaspetti commented on frontend_lib/test/fixture/status.js
> +  faIcon: 'fas fa-check-square',
```suggestion
  faIcon: 'far fa-check-square',
```

2021-02-02 09:45 UTC, Skylsmoi commented on backend/tracim_backend/models/data.py
> +#     #     'workspace': 'fas fa-university',
indeed, will fix anyways

2021-02-02 10:22 UTC, gbonaspetti requested changes

2021-02-02 10:22 UTC, gbonaspetti commented on frontend/src/container/PublicProfile.jsx
> +      <i className='fas fa-fw fa-image' /> {props.t('Maximum size: {{size}} MB', { size: MAXIMUM_IMAGE_SIZE / (1024 * 1024) })}
```suggestion
      <i className='far fa-fw fa-image' /> {props.t('Maximum size: {{size}} MB', { size: MAXIMUM_IMAGE_SIZE / (1024 * 1024) })}
```

2021-02-02 10:22 UTC, gbonaspetti commented on frontend/test/fixture/app/gallery.js
> +  faIcon: 'far fa-picture',
```suggestion
  faIcon: 'far fa-image',
```

2021-02-02 10:22 UTC, gbonaspetti commented on frontend_app_share_folder_advanced/src/component/NewUpload.jsx
> +                  <i className='fas fa-fw fa-repeat' />
```suggestion
                  <i className='fas fa-fw fa-redo' />
```

2021-02-02 10:22 UTC, gbonaspetti commented on frontend_lib/src/component/RefreshWarningMessage/RefreshWarningMessage.jsx
> +      className='fas fa-repeat'
```suggestion
      className='fas fa-redo'
```

2021-02-02 10:22 UTC, gbonaspetti commented on frontend_lib/src/component/ShareDownload/NewShareDownload.jsx
> +                  <i className='fas fa-fw fa-repeat' />
```suggestion
                  <i className='fas fa-fw fa-redo' />
```

2021-02-02 10:22 UTC, gbonaspetti commented on frontend/jsonserver/static_db.json
> +    "icon": "fas fa-fw fa-ticket",
```suggestion
    "icon": "fas fa-fw fa-ticket-alt",
```

2021-02-02 10:22 UTC, gbonaspetti commented on frontend/src/component/Dashboard/MoreInfo.jsx
> +          <i className='fas fa-windows' />
```suggestion
          <i className='fab fa-windows' />
```

2021-02-02 10:30 UTC, gbonaspetti requested changes

2021-02-02 10:30 UTC, gbonaspetti commented on backend/tracim_backend/models/data.py
> +        "deletion": "fas trash-alt",
```suggestion
        "deletion": "far trash-alt",
```

2021-02-02 10:30 UTC, gbonaspetti commented on frontend_lib/src/helper.js
> +  faIcon: 'fas fa-trash-alt',
```suggestion
  faIcon: 'far fa-trash-alt',
```

2021-02-02 10:31 UTC, Skylsmoi commented on frontend/src/component/FlashMessage.jsx
> +                <i className={classnames(`fas fa-${dataType.icon}`)} />
fixed

2021-02-02 10:31 UTC, Skylsmoi commented on frontend/src/component/Dashboard/WebdavInfo.jsx
> +          <i className='fas fa-hdd' />
fixed

2021-02-02 10:31 UTC, Skylsmoi commented on frontend/jsonserver/static_db.json
> +    "icon": "fas fa-fw fa-comments",
fixed

2021-02-02 10:31 UTC, Skylsmoi commented on frontend/jsonserver/static_db.json
> +    "icon": "fas fa-fw fa-file-image",
fixed

2021-02-02 10:32 UTC, Skylsmoi commented on frontend/jsonserver/static_db.json
> +    "icon": "fas fa-fw fa-file-code",
fixed

2021-02-02 10:32 UTC, Skylsmoi commented on frontend/jsonserver/static_db.json
> +    "icon": "fas fa-fw fa-file-text",
fixed

2021-02-02 10:33 UTC, Skylsmoi commented on frontend/src/component/PopupCreateContent/ContentType/FileContent.jsx
> +          <i className='fas fa-file-text-o' />
fixed

2021-02-02 10:33 UTC, Skylsmoi commented on frontend/src/component/GuestPage/UploadForm.jsx
> +            {props.t('Send')} <i className='fas fa-fw fa-paper-plane' />
fixed

2021-02-02 10:33 UTC, Skylsmoi commented on frontend/src/component/PopupCreateContent/ContentType/GenericContent.jsx
> +          <i className='fas fa-file-word-o' />
fixed

2021-02-02 10:33 UTC, Skylsmoi commented on frontend/src/component/Workspace/BtnExtandedAction.jsx
> +          <i className='fas fa-fw fa-picture' />
fixed

2021-02-02 10:34 UTC, Skylsmoi commented on frontend/test/fixture/app/thread.js
> +  faIcon: 'fas fa-comments',
fixed

2021-02-02 10:35 UTC, Skylsmoi commented on frontend/test/fixture/contentStatus/open.js
> +  faIcon: 'square',
fixed

2021-02-02 10:35 UTC, Skylsmoi commented on frontend/test/fixture/contentStatus/validated.js
> +  faIcon: 'fas fa-check-square',
fixed

2021-02-02 10:35 UTC, Skylsmoi commented on frontend_app_admin_workspace_user/src/component/AdminWorkspace.jsx
> +                        <i className='fas fa-fw fa-check-square-o' />
fixed

2021-02-02 10:36 UTC, Skylsmoi commented on frontend_app_file/src/component/PreviewComponent.jsx
> +              <i className='fas fa-file' />
fixed

2021-02-02 10:36 UTC, Skylsmoi commented on frontend_app_file/src/component/PreviewComponent.jsx
> +              <i className='fas fa-file-pdf' />
fixed

2021-02-02 10:36 UTC, Skylsmoi commented on frontend_app_folder_advanced/src/component/FolderAdvanced.jsx
> +            <i className='far fa-fw fa-trash-alt' />
fixed

2021-02-02 10:37 UTC, Skylsmoi commented on frontend_app_folder_advanced/src/component/FolderAdvanced.jsx
> +            <i className='far fa-fw fa-trash-alt' />
fixed

2021-02-02 10:37 UTC, Skylsmoi commented on frontend_app_folder_advanced/src/debug.js.sample
> +    faIcon: 'folder',
fixed

2021-02-02 10:38 UTC, Skylsmoi commented on frontend_app_gallery/src/container/Gallery.jsx
> +                  <i className='far fa-fw fa-trash-alt' />
fixed

2021-02-02 10:38 UTC, Skylsmoi commented on frontend_app_thread/src/debug.js.sample
> +    faIcon: 'comments',
fixed

2021-02-02 10:38 UTC, Skylsmoi commented on frontend_lib/src/component/FileDropzone/FileUploadList.jsx
> +            <i className='fas fa-fw fa-file-o m-1' />
fixed

2021-02-02 10:39 UTC, Skylsmoi commented on frontend_lib/src/component/NewMemberForm/NewMemberForm.jsx
> +                  <i className='name__adminmsg__icon fas fa-fw fa-lightbulb-o' />
fixed

2021-02-02 10:39 UTC, Skylsmoi commented on frontend_lib/src/component/OptionComponent/ArchiveDeleteContent.jsx
> +        <i className='far fa-fw fa-trash-alt' />
fixed

2021-02-02 10:40 UTC, Skylsmoi commented on frontend_lib/src/component/ShareLink/ShareLink.jsx
> +          <i className='fas fa-fw fa-files-o' />
fixed

2021-02-02 10:40 UTC, Skylsmoi commented on frontend_lib/src/component/ShareLink/ShareLink.jsx
> +            <i className='far fa-fw fa-trash-' />
fixed

2021-02-02 10:40 UTC, Skylsmoi commented on frontend_lib/src/component/Timeline/Timeline.jsx
> +                    <i className='fas fa-paper-plane' />
fixed

2021-02-02 10:41 UTC, Skylsmoi commented on frontend_lib/src/helper.js
> +  faIcon: 'fas fa-comment',
fixed

2021-02-02 10:41 UTC, Skylsmoi commented on frontend_lib/src/helper.js
> +  faIcon: 'fas fa-file-archive',
fixed

2021-02-02 10:42 UTC, Skylsmoi commented on frontend_lib/src/helper.js
> +  faIcon: 'fas fa-files',
fixed

2021-02-02 10:42 UTC, Skylsmoi commented on frontend_lib/src/helper.js
> +  faIcon: 'fas fa-trash-alt',
fixed

2021-02-02 10:43 UTC, Skylsmoi commented on frontend_lib/test/fixture/app/agenda.js
> +  faIcon: 'far fa-calendar-alt',
fixed

2021-02-02 10:43 UTC, Skylsmoi commented on frontend_lib/src/helper.js
> +  faIcon: 'fas fa-sun',
fixed

2021-02-02 10:44 UTC, Skylsmoi commented on frontend_lib/test/fixture/sidebarEntryList.js
> +    fa_icon: 'comments',
fixed

2021-02-02 10:44 UTC, Skylsmoi commented on frontend_lib/test/fixture/sidebarEntryList.js
> +    fa_icon: 'file-text',
fixed

2021-02-02 10:45 UTC, Skylsmoi commented on frontend_lib/test/fixture/sidebarEntryList.js
> +    fa_icon: 'picture',
fixed

2021-02-02 10:50 UTC, Skylsmoi commented on frontend_lib/test/fixture/status.js
> +  faIcon: 'fas fa-square',
fixed

2021-02-02 10:50 UTC, Skylsmoi commented on frontend_lib/test/fixture/status.js
> +  faIcon: 'fas fa-check-square',
fixed

2021-02-02 10:51 UTC, Skylsmoi commented on frontend/src/container/PublicProfile.jsx
> +      <i className='fas fa-fw fa-arrows-alt' /> {props.t('Recommended dimensions:')} {props.recommendedDimensions}<br />
fixed

2021-02-02 10:52 UTC, Skylsmoi commented on backend/tracim_backend/models/data.py
> +#     #     'workspace': 'fas fa-bank',
fixed

2021-02-02 10:52 UTC, Skylsmoi commented on backend/tracim_backend/applications/agenda/application.py
> +        fa_icon="far fa-calendar-alt",
fixed

2021-02-02 10:53 UTC, Skylsmoi commented on frontend/src/component/Dashboard/MoreInfo.jsx
> +            <i className='fas fa-calendar' />
fixed

2021-02-02 10:53 UTC, Skylsmoi commented on frontend/src/container/Header.jsx
> +                    <i className='far fa-fw fa-calendar-alt' />
fixed

2021-02-02 10:53 UTC, Skylsmoi commented on frontend_app_agenda/src/container/Agenda.jsx
> +          icon='fas fa-calendar'
fixed

2021-02-02 10:54 UTC, Skylsmoi commented on backend/tracim_backend/models/data.py
> +#     #     'closed-validated': 'fas fa-check-square-o',
fixed

2021-02-02 10:54 UTC, Skylsmoi commented on backend/tracim_backend/models/data.py
> +#     #     'closed-unvalidated': 'fas fa-close',
fixed

2021-02-02 10:55 UTC, Skylsmoi commented on backend/tracim_backend/models/data.py
> +#     #     'folder': 'fas fa-folder-open-o',
fixed

2021-02-02 10:55 UTC, Skylsmoi commented on frontend/jsonserver/static_db.json
> +    "icon": "fas fa-fw fa-code-fork",
fixed

2021-02-02 10:56 UTC, Skylsmoi commented on backend/tracim_backend/models/data.py
> +#     #     'page': 'fas fa-file-text-o',
fixed

2021-02-02 10:56 UTC, Skylsmoi commented on backend/tracim_backend/models/data.py
> +#     #     'event': 'fas fa-agenda-o',
fixed

2021-02-02 10:56 UTC, Skylsmoi commented on backend/tracim_backend/models/data.py
> +#     #     'event': 'fas fa-agenda-o',
fixed

2021-02-02 10:57 UTC, Skylsmoi commented on frontend_app_share_folder_advanced/src/component/NewUpload.jsx
> +                    <i className={state.hidePassword ? 'fas fa-fw fa-eye' : 'fas fa-fw fa-eye-slash'} />
fixed

2021-02-02 10:57 UTC, Skylsmoi commented on frontend_lib/src/component/ShareDownload/NewShareDownload.jsx
> +                    <i className={state.hidePassword ? 'fas fa-fw fa-eye' : 'fas fa-fw fa-eye-slash'} />
fixed

2021-02-02 10:57 UTC, Skylsmoi commented on frontend/src/component/Activity/Preview.jsx
> +        <i className='fas fa-eye-slash' />
fixed

2021-02-02 10:58 UTC, Skylsmoi commented on frontend_app_file/src/component/PreviewComponent.jsx
> +                        <i className='previewcomponent__fileimg__text-icon fas fa-eye-slash' style={{ color: props.color }} />
fixed

2021-02-02 10:58 UTC, Skylsmoi commented on frontend_app_html-document/src/css/index.styl
> +      .fa-file-text
fixed

2021-02-02 10:59 UTC, Skylsmoi commented on frontend_app_html-document/src/debug.js.sample
> +    faIcon: 'file-text',
fixed

2021-02-02 11:00 UTC, Skylsmoi commented on frontend/src/container/PublicProfile.jsx
> +      <i className='fas fa-fw fa-image' /> {props.t('Maximum size: {{size}} MB', { size: MAXIMUM_IMAGE_SIZE / (1024 * 1024) })}
fixed

2021-02-02 11:00 UTC, Skylsmoi commented on frontend/test/fixture/app/gallery.js
> +  faIcon: 'far fa-picture',
fixed

2021-02-02 11:00 UTC, Skylsmoi commented on frontend_app_share_folder_advanced/src/component/NewUpload.jsx
> +                  <i className='fas fa-fw fa-repeat' />
fixed

2021-02-02 11:01 UTC, Skylsmoi commented on frontend_lib/src/component/RefreshWarningMessage/RefreshWarningMessage.jsx
> +      className='fas fa-repeat'
fixed

2021-02-02 11:02 UTC, Skylsmoi commented on frontend_lib/src/component/ShareDownload/NewShareDownload.jsx
> +                  <i className='fas fa-fw fa-repeat' />
fixed

2021-02-02 11:02 UTC, Skylsmoi commented on frontend/jsonserver/static_db.json
> +    "icon": "fas fa-fw fa-ticket",
fixed

2021-02-02 11:02 UTC, Skylsmoi commented on frontend/src/component/Dashboard/MoreInfo.jsx
> +          <i className='fas fa-windows' />
fixed

2021-02-02 11:03 UTC, Skylsmoi commented on backend/tracim_backend/models/data.py
> +        "deletion": "fas trash-alt",
fixed

2021-02-02 11:03 UTC, Skylsmoi commented on frontend_lib/src/helper.js
> +  faIcon: 'fas fa-trash-alt',
fixed

2021-02-02 13:06 UTC, Skylsmoi commented
on commit "feat(front): add missing icon refactor" every tests passed but frontend unit test.

commit "feat(front): fix unit test" is only running frontend unit test

2021-02-02 13:19 UTC, gbonaspetti requested changes

2021-02-02 13:19 UTC, gbonaspetti commented on backend/tracim_backend/models/data.py
> +#     #     'open': 'fas fa-square-o',
```suggestion
#     #     'open': 'far fa-square',
```

2021-02-02 14:54 UTC, gbonaspetti approved these changes

2021-02-03 08:28 UTC, gbonaspetti approved these changes

2021-02-03 09:39 UTC, gbonaspetti approved these changes

2021-02-03 09:40 UTC, gbonaspetti commented
Tested on branch.

2021-02-03 13:28 UTC, merged