Feat(frontend): add  german translation
tracim/tracim pull request #4546
Opened 2021-04-19 09:25 UTC by MariePrandstetter

#4171

WIP 

## Checkpoints

**For developers**

- [ ] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [ ] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [ ] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2021-04-20 10:37 UTC, lebouquetin commented
Is it possible to include this in Tracim 3.8?

2021-04-29 15:22 UTC, gbonaspetti requested changes

2021-04-29 15:22 UTC, gbonaspetti commented on frontend/i18next.scanner/de/translation.json
> +  "New content": "New content",
```suggestion
  "New content": "Neuer Inhalt",
```
?

2021-04-29 15:22 UTC, gbonaspetti commented on frontend/i18next.scanner/de/translation.json
> +  "Loading recent activities…": "Laden der letzten Aktivitäten...",
```suggestion
  "Loading recent activities…": "Laden der letzten Aktivitäten…",
```

2021-04-29 15:22 UTC, gbonaspetti commented on frontend_lib/i18next.scanner/de/translation.json
> +  "Translation pending…": "Übersetzung ausstehend...",
```suggestion
  "Translation pending…": "Übersetzung ausstehend…",
```

2021-04-29 15:24 UTC, gbonaspetti commented
Missing translation at frontend/src/component/Search/DateFilter.jsx

2021-05-03 13:16 UTC, gbonaspetti requested changes

2021-05-03 13:16 UTC, gbonaspetti commented on frontend/src/component/Search/DateFilter.jsx
> +      de: 'TT/MM/JJJJ'
I think this part is automatic, not the translation, the place holder translation is in the i18next file, so it should be something like that according to how the date is presented 
```suggestion
      de: 'dd/MM/yyyy'
```

2021-05-03 13:23 UTC, inkhey commented on backend/tracim_backend/locale/de/LC_MESSAGES/tracim_backend.po
> +"Generated-By: Babel 2.6.0\n"
Not really important but some value here doesn't look make much sense Language-Team, Report-Msgid-Bugs-To.
but also "ORGANIZATION" in the header.
We should probably add a small issue about configuring theses value properly and take some time just to understand the goal or not of these metadata.

2021-05-03 13:39 UTC, grignards commented on frontend/src/util/tinymceInit.js
> +          return 'pt_DE'
Shouldn't it be:

```suggestion
          return 'de_DE'
```

2021-05-03 13:55 UTC, inkhey commented
updating the file https://github.com/tracim/tracim/blob/b6a8aadc5445b0d204ca8729b3ef24186035af80/frontend/dist/assets/branding.sample/welcome-simple-text.html may also make sense to be explicit about the fact that german is now available.

2021-05-03 14:56 UTC, gbonaspetti approved these changes

2021-05-04 13:00 UTC, gbonaspetti commented
Tested on branch

2021-05-05 12:43 UTC, merged