new release_04.01.00
tracim/tracim pull request #5062
Opened 2021-11-03 10:06 UTC by MariePrandstetter

## Checkpoints

**For developers**

- [ ] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [ ] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [ ] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2021-11-03 10:17 UTC, PhilippeAccorsi requested changes

2021-11-03 10:17 UTC, PhilippeAccorsi commented on changelog.md
> +# 4.1.0 / 2021-10-29
wrong version number

2021-11-03 10:17 UTC, PhilippeAccorsi commented on changelog.md
> +# 4.1.0 / 2021-10-29
and date

2021-11-03 10:17 UTC, PhilippeAccorsi commented on changelog.md
> +
Please add one more space between two version.

2021-11-03 10:58 UTC, grignards approved these changes

2021-11-03 15:52 UTC, PhilippeAccorsi approved these changes

2021-11-03 15:54 UTC, PhilippeAccorsi commented
@MariePrandstetter Can you add an issue related to this version ?

2021-11-03 15:55 UTC, PhilippeAccorsi commented
Also: if you add fixed issues in this version before merge, you need to change the date of the release.

2021-11-03 16:17 UTC, PhilippeAccorsi requested changes

2021-11-03 16:17 UTC, PhilippeAccorsi commented on changelog.md
> +[#4895](https://github.com/tracim/tracim/issues/4895)
Missing `,` at end of first issue
ordering of issue is not good

2021-11-04 11:24 UTC, PhilippeAccorsi approved these changes

2021-11-04 14:01 UTC, merged