misc: write functional test for the timeline
tracim/tracim pull request #5106
Opened 2021-11-18 14:47 UTC by MariePrandstetter

## Checkpoints

**For developers**

- [ ] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [ ] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [ ] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2021-11-18 16:40 UTC, gbonaspetti requested changes

2021-11-18 16:40 UTC, gbonaspetti commented on functionnal_tests/cypress/integration/app_file/switch_between_apps_spec.js
> +//  mettre ce file dans un autre dossier
Forgotten comment

2021-11-18 16:40 UTC, gbonaspetti commented on functionnal_tests/cypress/integration/app_file/switch_between_apps_spec.js
> +        // 2021-11-18 - MB - Switching to another file app
```suggestion
        // INFO - MB - 2021-11-18 - Switching to another file app
```

2021-11-18 16:40 UTC, gbonaspetti commented on functionnal_tests/cypress/integration/app_file/switch_between_apps_spec.js
> +        // 2021-11-18 - MB - Switching again
```suggestion
        // INFO - MB - 2021-11-18 - Switching again
```

2021-11-18 16:40 UTC, gbonaspetti commented on functionnal_tests/cypress/integration/app_file/switch_between_apps_spec.js
> +        .click()
Is the tabulation correct?

2021-11-19 13:57 UTC, Haskaris commented on functionnal_tests/cypress/integration/app_file/switch_between_apps_spec.js
> +        cy.get(formatTag({ selectorName: s.SIDEBAR_ARROW }))
```suggestion
        cy.getTag({ selectorName: s.SIDEBAR_ARROW })
```

2021-11-19 13:59 UTC, Haskaris commented on functionnal_tests/cypress/integration/app_file/switch_between_apps_spec.js
> +        cy.get(formatTag({ selectorName: s.SIDEBAR_ARROW }))
You can gain clarity using `getTag()` instead of `get(formatTag())` since `getTag()` is already `cy.get` calling `formatTag()`.

2021-11-22 16:42 UTC, gbonaspetti approved these changes

2021-11-24 09:26 UTC, merged