Fix(frontend) improve performances on space or user list in administration page
tracim/tracim pull request #5120
Opened 2021-11-24 13:50 UTC by Haskaris

See #3933

## Checkpoints

**For developers**

- [ ] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [x] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2021-11-24 14:42 UTC, inkhey requested changes
Can you update some api test to check theses endpoint in backend ?

2021-11-25 09:35 UTC, gbonaspetti requested changes

2021-11-25 09:35 UTC, gbonaspetti commented on frontend_app_admin_workspace_user/src/container/AdminWorkspaceUser.jsx
> -
getDetailedUser uses this function too

2021-11-25 10:46 UTC, Haskaris commented on frontend_app_admin_workspace_user/src/container/AdminWorkspaceUser.jsx
> -
Thanks!

2021-11-25 10:47 UTC, Haskaris commented
I've converted this PR to draft since my changes are involving more changes than I thought

2021-11-25 16:02 UTC, inkhey approved these changes
:+1:

2021-11-26 12:48 UTC, raphj commented on frontend_app_admin_workspace_user/test/container/AdminWorkspaceUser.spec.js
> +          console.log(workspaceList)
Leftover?

2021-11-26 12:48 UTC, raphj commented on frontend_app_admin_workspace_user/test/setup.js
> +import sinon from 'sinon'
Leftover?

2021-11-26 12:48 UTC, raphj commented on frontend_app_admin_workspace_user/test/setup.js
> +sinon.stub(console, 'log')
Leftover?

2021-12-07 16:17 UTC, gbonaspetti approved these changes

2021-12-08 09:10 UTC, gbonaspetti commented
Tested on branch

2021-12-08 10:45 UTC, merged