Feat/5129  improve kanban
tracim/tracim pull request #5150
Opened 2021-12-06 16:06 UTC by gbonaspetti

#5129 

## Checkpoints

**For developers**

- [ ] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [ ] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [ ] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2021-12-07 09:12 UTC, inkhey approved these changes
Ok for the backend part

2021-12-08 08:27 UTC, Haskaris commented on frontend_app_kanban/i18next.scanner/de/translation.json
> +  "Value:": "__NOT_TRANSLATED__",
Still need translation here

2021-12-08 08:44 UTC, Haskaris commented on frontend_app_kanban/i18next.scanner/de/translation.json
> +  "Value:": "__NOT_TRANSLATED__",
Still need translation here

2021-12-08 08:44 UTC, Haskaris commented on backend/tracim_backend/models/data.py
> +                    pass
```suggestion
```
No need of `pass` here

2021-12-08 09:21 UTC, knodelle approved these changes

2021-12-08 10:44 UTC, Haskaris approved these changes

2021-12-08 15:29 UTC, inkhey requested changes

2021-12-08 15:29 UTC, inkhey commented on frontend_lib/src/component/Timeline/Revision.jsx
> +  console.log("REVISION")
remove this.

2021-12-08 15:31 UTC, gbonaspetti commented on frontend_lib/src/component/Timeline/Revision.jsx
> +  console.log("REVISION")
done

2021-12-08 15:33 UTC, inkhey approved these changes
ok for backend.

2021-12-08 15:46 UTC, knodelle commented
tested on branch

2021-12-09 09:11 UTC, inkhey approved these changes

2021-12-09 10:15 UTC, gbonaspetti commented
The tests frontend are canceled to allow to go faster, but they passed in the other commits and follow the modifications are just in backend.

2021-12-09 10:17 UTC, merged