fix(frontend): display call popups on ios and open as links
tracim/tracim pull request #5243
Opened 2022-01-05 11:15 UTC by knodelle

Issue : #5070

## Checkpoints

**For developers**

- [ ] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [ ] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [ ] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2022-01-05 13:02 UTC, gbonaspetti requested changes
there is a deletion of backend/development.ini.sample file

2022-01-05 16:03 UTC, gbonaspetti commented
Tested on branch (not on safari, but it will be tested during integration).

2022-01-05 16:22 UTC, merged

2022-01-13 16:24 UTC, raphj commented on frontend/src/container/Tracim.jsx
> +        const notificationString = tlm.fields.user_call.caller.public_name + props.t(' is calling you on Tracim')
maybe put the name in the translation string as a placeholder. This with make it easier to translate

props.t('{name} is calling you on Tracim', ...)

2022-01-13 16:24 UTC, raphj commented on frontend/src/container/Tracim.jsx
> +            new Notification(notificationString, notificationOptions) // eslint-disable-line
It would be better to disable the specific eslint error here

2022-01-13 16:25 UTC, raphj commented on frontend/src/container/Tracim.jsx
> +                  {/* FIXME - MB - 2022-01-05 - a LinkButton should be created with the same style that IconButton
the same style **as**

2022-01-13 16:26 UTC, raphj commented on frontend/src/container/Tracim.jsx
> +                  {/* FIXME - MB - 2022-01-05 - a LinkButton should be created with the same style that IconButton
as

2022-01-13 16:26 UTC, raphj commented
I commented on a merged pull request.... never mind.