feat(frontend): add caldav arabic translation
tracim/tracim pull request #5504
Opened 2022-03-08 16:34 UTC by knodelle

## Checkpoints

**For developers**

- [ ] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [ ] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [ ] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2022-03-09 14:21 UTC, knodelle commented
Some translations are missing, they will be added before this pr is closed

2022-03-11 13:23 UTC, Haskaris approved these changes

2022-03-15 09:16 UTC, gbonaspetti commented on frontend/dist/assets/_caldavzap/localization.js
> +	todoUncompletedNextNav: 'Show next uncompleted instance',
```suggestion
	todoPrevNav: 'عرض المنصّة السابقة',
	todoNextNav: 'عرض المنصّة الموالية',
	todoUncompletedPrevNav: 'عرض المنصّة السابقة غير المكتملة',
	todoUncompletedNextNav: 'عرض المنصّة الموالية غير المكتملة',
```

2022-03-15 09:19 UTC, gbonaspetti commented on frontend/dist/assets/_caldavzap/localization.js
> +	unsupportedBrowser: 'ملاحظة : لا يمكن تحمل المتصفح الذي تستعمله',
```suggestion
	unsupportedBrowser: 'ملاحظة: لا يمكن تحمل المتصفح الذي تستخدمه!',
```

2022-03-15 09:24 UTC, gbonaspetti commented on frontend/dist/assets/_caldavzap/localization.js
> +	txtErorInput: "خطأ : /التسجيل غير ممكن/' الرجاء تصحيح القيم المبرزة",
```suggestion
	txtAllDeletedTodo: 'نجاح: تم حذف المهمة!',
	txtAllDeleted: 'نجاح: تم حذف المناسبة!',

	txtNotChooseTodo: 'خطأ: يجب اختيار رزنامة!',
	txtNotChoose: 'خطأ: يجب اختيار رزنامة!',

	txtErrorDates: 'خطأ: تاريخ البداية يجب أن يسبق تاريخ النهاية!',
	txtErrorDatesTodo: 'خطأ: تاريخ البداية يجب أن يسبق تاريخ النهاية!',

	txtErorInputTodo: 'التسجيل غير ممكن: الرجاء تصحيح القيم غير الصحيحة!',
	txtDateTimeErrorTodo: 'يجب اختيار تاريخ و ساعة!',

	txtErorInput: "خطأ: /التسجيل غير ممكن'\ : الرجاء تصحيح القيم المبرزة!",
```

2022-03-15 09:36 UTC, gbonaspetti requested changes

2022-03-15 09:36 UTC, gbonaspetti commented on frontend/dist/assets/_caldavzap/localization.js
> +	txtCalendarTODO: 'Calendar',
```suggestion
	txtCalendarTODO: 'رزنامة',
```

2022-03-15 09:36 UTC, gbonaspetti commented on frontend/dist/assets/_caldavzap/localization.js
> +	pholderTimeTo: 'Time to',
```suggestion
	pholderDateFrom: 'تاريخ البداية',
	pholderTimeFrom: 'ساعة البداية',
	pholderDateTo: 'تاريخ النهاية',
	pholderTimeTo: 'ساعة النهاية',
```

2022-03-15 09:39 UTC, gbonaspetti requested changes

2022-03-15 09:39 UTC, gbonaspetti commented on frontend/dist/assets/_caldavzap/localization.js
> +	txtEnabledCalendars: 'Enabled Calendars',
```suggestion
	txtEnabledCalendars: 'تفعيل الرزنامات',
```

2022-03-15 09:39 UTC, gbonaspetti commented on frontend/dist/assets/_caldavzap/localization.js
> +	txtSelectCalendar: 'Select a calendar',
```suggestion
	txtEventCalendar: 'رزنامة',
	txtSelectCalendar: 'اختيار رزنامة',
```

2022-03-15 09:39 UTC, gbonaspetti commented on frontend/dist/assets/_caldavzap/localization.js
> +	eventNextNav: 'Show next instance',
```suggestion
	eventPrevNav: 'عرض المنصّة السابقة',
	eventNextNav: 'عرض المنصّة الموالية',
```

2022-03-15 09:40 UTC, gbonaspetti requested changes

2022-03-15 09:40 UTC, gbonaspetti commented on frontend/dist/assets/_caldavzap/localization.js
> +	_default_datepicker_format_: 'يوم/شهر/سنة',
dd/mm/yyyy

2022-03-15 09:41 UTC, gbonaspetti requested changes

2022-03-15 09:41 UTC, gbonaspetti commented on frontend/dist/assets/_caldavzap/localization.js
> +	_default_datepicker_format_: 'يوم/شهر/سنة',
```suggestion
	_default_datepicker_format_: 'dd/mm/yyyy',
```

2022-03-15 10:39 UTC, gbonaspetti commented
Tested on branch

2022-03-15 15:58 UTC, merged