feat(backend): add connected user role to space endpoint
tracim/tracim pull request #5658
Opened 2022-05-16 09:07 UTC by Haskaris

Issue ref #1897 

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2022-05-16 10:23 UTC, inkhey approved these changes

2022-05-16 10:33 UTC, inkhey commented on backend/tracim_backend/models/context_models.py
> +
oh i didn't read the spec correctly. i'm pluzzed by the ticket, this broke the REST spirit of the API.

2022-05-16 10:35 UTC, inkhey requested changes
need discussion about the endpoint specification.

2022-05-17 08:44 UTC, Haskaris commented
See https://github.com/tracim/tracim/issues/1897#issuecomment-1128592496

2022-05-17 08:44 UTC, closed without merging