Fix/5687  role choice when adding member to a space
tracim/tracim pull request #5714
Opened 2022-06-16 12:37 UTC by wwalden

#5687

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [x] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [x] Manual, quality tests have been done

2022-06-17 10:22 UTC, gbonaspetti requested changes

2022-06-17 10:22 UTC, gbonaspetti commented on frontend/src/container/Dashboard.jsx
> +      this.setState({ newMember: { ...state.newMember, role: props.currentWorkspace.defaultRole } })
```suggestion
      this.setState(prev => ({ newMember: { ...prev.newMember, role: props.currentWorkspace.defaultRole } }))
```

2022-06-17 10:22 UTC, gbonaspetti commented on frontend_app_workspace_advanced/src/container/WorkspaceAdvanced.jsx
> +    this.setState({ default_temp_user_role: content.default_user_role})
There is a reason to use snake case here?

2022-06-20 12:27 UTC, gbonaspetti approved these changes

2022-06-20 14:52 UTC, Haskaris approved these changes

2022-06-20 15:14 UTC, Haskaris commented
Tested on branch.

2022-06-20 15:17 UTC, merged