Fix/5685 missing set username popup
tracim/tracim pull request #5737
Opened 2022-06-27 14:32 UTC by wwalden

#5685

## Checkpoints

**For developers**

- [ ] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [ ] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [ ] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2022-06-28 07:44 UTC, gbonaspetti requested changes

2022-06-28 07:44 UTC, gbonaspetti commented on frontend/src/container/Tracim.jsx
> +
```suggestion
        {((!props.user.username && Cookies.get(COOKIE_FRONTEND.SHOW_USERNAME_POPUP) === 'true' && props.user.config.display_username_popup !== 'false') &&
          <CardPopupUsername />
        )}

```



The hard coded strings 'true' and 'false' can't be consts or real booleans ?

2022-06-28 07:44 UTC, gbonaspetti commented on frontend/src/container/CardPopupUsername.jsx
> +          {!this.state.isUsernameValid && (
```suggestion
          {!state.isUsernameValid && (
```

2022-06-28 07:44 UTC, gbonaspetti commented on frontend/src/container/CardPopupUsername.jsx
> +              {this.state.usernameInvalidMsg}
```suggestion
              {state.usernameInvalidMsg}
```

2022-06-28 07:44 UTC, gbonaspetti commented on frontend/src/container/CardPopupUsername.jsx
> +          {this.state.isUsernameValid && (
```suggestion
          {state.isUsernameValid && (
```

2022-06-28 07:44 UTC, gbonaspetti commented on frontend/src/container/CardPopupUsername.jsx
> +          {this.state.newUsername !== '' && (
```suggestion
          {state.newUsername !== '' && (
```

2022-06-28 07:44 UTC, gbonaspetti commented on frontend/src/container/CardPopupUsername.jsx
> +                value={this.state.password}
```suggestion
                value={state.password}
```

2022-06-28 07:44 UTC, gbonaspetti commented on frontend/src/container/CardPopupUsername.jsx
> +  handleChangeNewUsername = async e => {
Why async ?

2022-06-28 15:39 UTC, gbonaspetti commented on functionnal_tests/cypress/integration/login/username_popup_spec.js
> +      cy.get('.flashmessage__container__content__text__title').contains('Error').should('not.exist')
```suggestion
      cy.contains('.flashmessage__container__content__text__title', 'Error').should('not.exist')
      cy.get('.flashmessage').contains('Invalid password')
    })

    it('should be able to set username', function () {
      cy.get(usernameInput).type(newUsername)
      cy.get(passwordInput).type(userWithoutUsername.password)
      cy.get(confirmButton).click()
      cy.contains('.flashmessage__container__content__text__title', 'Error').should('not.exist')
```

2022-06-29 08:42 UTC, wwalden reviewed
ok

2022-06-29 08:43 UTC, wwalden reviewed
ok

2022-06-29 08:43 UTC, wwalden reviewed
ok

2022-06-29 08:43 UTC, wwalden reviewed
ok

2022-06-29 08:45 UTC, wwalden reviewed
ok

2022-06-29 08:46 UTC, gbonaspetti approved these changes

2022-06-29 10:06 UTC, gbonaspetti commented
When the user chose to not show the popup again, in the next time he log in, we have the popup that appears for some milliseconds and disappears after (see gif bellow). I think it is a small bug and we can merge with it. 
It would be nice to make an issue about it.
![username](https://user-images.githubusercontent.com/35422692/176410792-cc4d5288-83f9-4c34-87f0-a57b19c0a420.gif)



Tested on branch

2022-06-29 13:50 UTC, merged