fix todos rights
tracim/tracim pull request #5782
Opened 2022-07-12 08:50 UTC by Haskaris

Issue #5781 

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
~~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~~ See #5726 
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2022-07-13 10:08 UTC, inkhey requested changes

2022-07-13 10:08 UTC, inkhey commented on backend/tracim_backend/lib/utils/authorization.py
> +    is_assignee, is_todo_owner, is_content_manager, is_workspace_manager,
This mean reader can edit todo ? Are we sure we want this ?
Can you update doc/roles.md with the todo rules ?

2022-07-13 15:04 UTC, inkhey requested changes

2022-07-13 15:04 UTC, inkhey commented on backend/doc/roles.md
> +| update todo (check/uncheck) | no | yes | no | yes | no | yes | yes | yes | yes |
```suggestion
| update todo (check/uncheck) | no | yes | no | no | yes | yes | yes | yes | yes |
```

2022-07-13 15:07 UTC, inkhey approved these changes

2022-07-15 07:08 UTC, gbonaspetti commented
Tested on branch

2022-07-15 07:19 UTC, merged