Doc: update docker-compose
tracim/tracim pull request #5801
Opened 2022-07-22 10:10 UTC by gbonaspetti

## Checkpoints

**For developers**

- [ ] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [ ] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [ ] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2022-07-22 10:11 UTC, gbonaspetti commented on backend/README.md
> +The [docker-compose.yml](docker compose.yml) file lists the services needed for testing the Tracim backend. Default environment variables used by the containers are written in the [.env](.env) file n
```suggestion
The [docker-compose.yml](docker-compose.yml) file lists the services needed for testing the Tracim backend. Default environment variables used by the containers are written in the [.env](.env) file next to `docker-compose.yml`.
```

2022-07-22 12:35 UTC, PhilippeAccorsi requested changes
A small change.
Need to test on new dev installation if all script and test working correctly.

2022-07-22 12:35 UTC, PhilippeAccorsi commented on backend/.env
> -# Those are default values for docker-compose*.yml files
Do not remove `-` here.

2022-07-22 13:08 UTC, gbonaspetti commented on backend/.env
> +# Those are default values for docker compose*.yml files
```suggestion
# Those are default values for docker-compose*.yml files
```

2022-07-25 09:02 UTC, Quiwy reviewed
For now, the CI is blocked because it asks confirmation for package installation, so we need to accept changes when calling `apt-get`, like it was done [here](https://github.com/tracim/tracim/pull/5801/files#diff-9bde39cdfbde0898c6958301a2e6be457f381c6f32bf34e9d75cde2d74436b31L6)

2022-07-25 09:02 UTC, Quiwy commented on concourse/scripts/install_docker
> +apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
```suggestion
apt-get install -qy docker-ce docker-ce-cli containerd.io docker-compose-plugin
```

2022-07-25 09:02 UTC, Quiwy commented on concourse/scripts/install_docker
> +apt-get install \
```suggestion
apt-get install -qy \
```

2022-07-26 12:00 UTC, PhilippeAccorsi approved these changes

2022-07-26 14:23 UTC, gbonaspetti commented
Tested on branch by @Quiwy

2022-07-26 16:07 UTC, merged