Feat/use prismjs to display code
tracim/tracim pull request #5889
Opened 2022-09-28 13:13 UTC by gbonaspetti

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2022-10-05 07:44 UTC, Haskaris requested changes
Looks good to me, but maybe we can format `prism.css` so it's human readable?
On Visual Studio Code you can use `ctrl+shit+i` to format a document

2022-10-05 09:05 UTC, Skylsmoi requested changes

2022-10-05 09:05 UTC, Skylsmoi commented on frontend_lib/src/component/HTMLContent/HTMLContent.jsx
> +  Also, a new css file has been added in frontend/dist/assets/prism.css.
I'd like you to put the prism.css file in a prism folder instead of at the root of assets/

2022-10-05 09:07 UTC, Skylsmoi commented
@Haskaris @gbonaspetti About the minification of prism.css, it appears that the file isn't bundled but included directly in the web page.
So I would recommend to keep it minified. You can however, add an unminified copy that won't be used in production

2022-10-07 12:23 UTC, Quiwy commented
Tested on branch, seems fine to me.
Just 3 points :

1. Lines numbers and coloration does not appears directly when saving a note, we need to reload the page
![line_color](https://user-images.githubusercontent.com/20048264/194548875-6d9aef75-1f44-483f-ab5a-0746b3da9d7d.gif)

2. Why loading all features of prism (cf https://github.com/tracim/tracim/blob/dd1ad9aa21d44af317539f6ad1ca01e5ae5ae073/frontend/dist/assets/prism/prism.css#L2 ) if we only support 10 of them ?

3. Maybe it's not necessary to support all of them, but I think we could add more supported extensions. Things I'm personally using a lot (but may need some internal discussion) (will commit about it) :
- apacheconf
- nginx
- diff
- jinja2
- docker/dockerfile
- git
- jq
- json
- markdown
- rust
- yaml

2022-10-11 12:31 UTC, Quiwy commented
Tested on branch, working perfectly :sunglasses:

2022-10-11 12:59 UTC, Skylsmoi commented on frontend_lib/src/appContentFactory.js
> +    appContentCustomEventHandlerAllAppChangeLanguage = (newLang, codeSampleLanguageList, setState, i18n, isTimelineWysiwyg, changeNewCommentHandler = null) => {
using 
import store from '[...]/store.js"
store.getState()

2022-10-12 10:00 UTC, Skylsmoi requested changes

2022-10-12 10:00 UTC, Skylsmoi commented on frontend/src/util/tinymceInit.js
> +      codesample_languages: reduxStore.system.config.ui__notes__code_sample_languages,
as seen together, this variable might not be initialized.
wrap it around an if and display a console.error containing description of error and pointing to the issue related to this dev. And add a comment in the issue explaining that the solution would be to add an await to this.loadAppConfig() in Tracim.jsx

2022-10-12 13:49 UTC, gbonaspetti commented on frontend/src/util/tinymceInit.js
> +    const reduxStore = store.getState()
```suggestion
    let reduxStore = store.getState()
    
    if (!reduxStore.system || !reduxStore.system.config) {
      console.error('The redux system variable is not initialized. See #5890 GitHub issue for details.')
      reduxStore = { system: { config: { ui__notes__code_sample_languages: [] } } }
    }
```

2022-10-12 13:59 UTC, gbonaspetti commented on frontend/src/util/tinymceInit.js
> +    if (!reduxStore.system || !reduxStore.system.config) {
```suggestion
    if (Object.keys(reduxStore.system.config).length === 0) {
```

2022-10-12 14:15 UTC, Skylsmoi approved these changes
Don't forget to add information about redux initialization in an issue's comment

2022-10-12 21:40 UTC, merged