feat(frontend): display kanban in activities feeds
tracim/tracim pull request #5958
Opened 2022-10-21 08:54 UTC by Haskaris

Issue #5957 

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [x] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2022-10-21 09:33 UTC, gbonaspetti requested changes

2022-10-21 09:33 UTC, gbonaspetti commented on frontend/src/container/withActivity.jsx
> +    isActuality = (activity) => {
`isNews`? We translate "Actualités" to "News" on the interface.

2022-10-21 09:33 UTC, gbonaspetti commented on frontend/src/container/withActivity.jsx
> +      return isActuality || hasSpace
If I understand well you transformed 
```
(activity.content.content_namespace !== CONTENT_NAMESPACE.PUBLICATION || !activity.newestMessage.fields.workspace)
```
to
```
!(isActuality || hasSpace)
```
If yes, that is not the same thing.

A | B | ∼ A ∨ ∼ B
-- | -- | --
1 | 1 | 0
1 | 0 | 1
0 | 1 | 1
0 | 0 | 1


A | B | ∼ ( A ∨ B )
-- | -- | --
1 | 1 | 0
1 | 0 | 0
0 | 1 | 0
0 | 0 | 1

You should return isActuality && hasSpace here.



A | B | ∼ ( A ∧ B )
-- | -- | --
1 | 1 | 0
1 | 0 | 1
0 | 1 | 1
0 | 0 | 1

2022-10-21 13:54 UTC, gbonaspetti approved these changes

2022-10-24 08:21 UTC, Quiwy commented
Tested on branch

2022-10-24 08:24 UTC, merged