Fix(backend, frontend): reduce the number of communication during a copy from webdav
tracim/tracim pull request #6069
Opened 2022-12-16 10:47 UTC by Haskaris

Disable event creation (TLMs) during a copy and send only one event (TLM) after the copy is finished.
Reduce the amount of API calls for a modified commentary (regression during #5846)

Issue linked #6068 

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
~~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~~
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2022-12-16 12:54 UTC, grignards requested changes

2022-12-16 12:54 UTC, grignards commented on backend/tracim_backend/lib/utils/request.py
> +            )
The hook should probably executed only if an exception didn't occur:
```suggestion
        try:
            yield
        finally:
            self._disable_events = False
        else:
            self.plugin_manager.hook.on_batched_events_finished(
                operation_type=operation_type, obj=obj, context=self
            )
```

2022-12-16 13:58 UTC, grignards approved these changes

2022-12-16 16:02 UTC, grignards commented
Tested on branch.

2022-12-20 17:50 UTC, Skylsmoi approved these changes

2022-12-20 17:51 UTC, merged