Fix/4611  chrome performance workaround
tracim/tracim pull request #6227
Opened 2023-08-02 08:41 UTC by floreal15

To enable correct performance when base64 images are inserted.

https://github.com/tracim/tracim/issues/4591
https://github.com/tracim/tracim/issues/4611

Old hack creates new bugs : https://github.com/tracim/tracim/issues/6224

Which is fixed in this PR but there is a bug where when editing a content the popup will open empty ( seems to happen after reloading the page and if the devtools are closed )

## Checkpoints

**For developers**

- [ ] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [ ] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [ ] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

2023-11-03 15:21 UTC, PhilippeAccorsi requested changes
Not sure but I seen some files related to tracim 4.6.1
I don't know if it is ok now (version 4.6.2 available.

Maybe merge develop in this branch first.

2024-07-29 08:09 UTC, Millefeuille42 commented
This PR has been stale for half a year, It introduces new bugs that should be fixed before merge. If we don't want / can't do these fixes for now, we should close the PR

2025-03-13 09:45 UTC, lebouquetin commented
@Skylsmoi what about closing this PR (+ associated issue?)

2025-03-13 09:55 UTC, Skylsmoi commented
The issue still exists (I just tested it).
This PR can be closed because of how stall it is. I wouldn't close the issues though

2025-03-13 10:50 UTC, lebouquetin commented
ok so lets close PR + delete associated branch @Skylsmoi

2025-03-13 15:33 UTC, closed without merging

2025-03-13 15:33 UTC, Skylsmoi commented
done